### ISSUE TITLE
Better database.yml config

### ISSUE THREAD

**Issue by jsanguinetticds** [ruby-dojo-cds/office-management#11]
Let's make user and pass environment variables and use a common default for development and test.
Something like:
```
default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode
  pool:  <%= ENV['DATABASE_POOL_SIZE'] || 5 %>

development:
  <<: *default
  database: office_management-development

test:
  <<: *default
  database: office_management-test
```
